version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build complete. Uploading to S3...

artifacts:
  files:
    - '**/*'

post_build:
  commands:
    - aws s3 cp ./ s3://my-sample-html-site/ --recursive
